Adapt workflows to new repo

diff --git a/.github/workflows/quint.yml b/.github/workflows/quint.yml
--- a/.github/workflows/quint.yml
+++ b/.github/workflows/quint.yml
@@ -1,15 +1,56 @@
-name: Quint simulations and tests
+name: Quint checks
 
 on:
   push:
     branches:
       - main
+    paths:
+      - "grug/jellyfish-merkle/spec/**"
   pull_request:
+    paths:
+      - "grug/jellyfish-merkle/spec/**"
 
 jobs:
+  lmt-check:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./grug/jellyfish-merkle/spec
+    steps:
+    # Step 1: Checkout the repository
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    # Step 2: Install Go
+    - name: Install Go
+      uses: actions/setup-go@v4
+      with:
+        go-version: '1.20' # Replace with the required Go version
+
+    # Step 3: Clone and build `lmt`
+    - name: Build LMT
+      run: |
+        go install github.com/driusan/lmt@latest
+        export PATH=$PATH:$(go env GOPATH)/bin
+
+    # Step 4: Run `lmt` and fail if differences are detected
+    - name: Run LMT
+      run: |
+        lmt docs/proofs.md
+        lmt docs/invariants.md
+        lmt docs/tree_manipulation.md
+        lmt docs/grug_ics23.md
+        lmt docs/proof_types.md
+        # Check that it is up to date
+        git diff --exit-code \
+          || ( echo ">>> ERROR: Tangled files are out of sync." &&  exit 1)
+
   quint-typecheck:
     name: Typecheck
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./grug/jellyfish-merkle/spec
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v3
@@ -21,6 +62,9 @@ jobs:
   quint-test:
     name: Test
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: ./grug/jellyfish-merkle/spec
     env:
       MAX_SAMPLES: 100
     steps:
@@ -36,7 +80,7 @@ jobs:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./quint
+        working-directory: ./grug/jellyfish-merkle/spec/quint
     env:
       MAX_SAMPLES: 100
       MAX_STEPS: 3
@@ -53,7 +97,7 @@ jobs:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./quint
+        working-directory: ./grug/jellyfish-merkle/spec/quint
     env:
       MAX_SAMPLES: 100
       MAX_STEPS: 3
@@ -70,7 +114,7 @@ jobs:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./quint
+        working-directory: ./grug/jellyfish-merkle/spec/quint
     env:
       MAX_SAMPLES: 100
       MAX_STEPS: 3
@@ -87,7 +131,7 @@ jobs:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./quint
+        working-directory: ./grug/jellyfish-merkle/spec/quint
     env:
       MAX_SAMPLES: 100
       MAX_STEPS: 3
