spec: run formatter and address linter issues in JMT spec (#378)
* run formatters

* fix indentation in the CI yaml file

* address various markdownlint issues

* revert auto-generated table of contents by vscode

* rename github workflow

diff --git a/.github/workflows/quint.yml b/.github/workflows/quint.yml
--- a/.github/workflows/quint.yml
+++ b/.github/workflows/quint.yml
@@ -1,4 +1,4 @@
-name: Quint checks
+name: Quint
 
 on:
   push:
@@ -17,33 +17,33 @@ jobs:
       run:
         working-directory: ./grug/jellyfish-merkle/spec
     steps:
-    # Step 1: Checkout the repository
-    - name: Checkout code
-      uses: actions/checkout@v3
+      # Step 1: Checkout the repository
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    # Step 2: Install Go
-    - name: Install Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '1.20' # Replace with the required Go version
+      # Step 2: Install Go
+      - name: Install Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: '1.20' # Replace with the required Go version
 
-    # Step 3: Clone and build `lmt`
-    - name: Build LMT
-      run: |
-        go install github.com/driusan/lmt@latest
-        export PATH=$PATH:$(go env GOPATH)/bin
+      # Step 3: Clone and build `lmt`
+      - name: Build LMT
+        run: |
+          go install github.com/driusan/lmt@latest
+          export PATH=$PATH:$(go env GOPATH)/bin
 
-    # Step 4: Run `lmt` and fail if differences are detected
-    - name: Run LMT
-      run: |
-        lmt docs/proofs.md
-        lmt docs/invariants.md
-        lmt docs/tree_manipulation.md
-        lmt docs/grug_ics23.md
-        lmt docs/proof_types.md
-        # Check that it is up to date
-        git diff --exit-code \
-          || ( echo ">>> ERROR: Tangled files are out of sync." &&  exit 1)
+      # Step 4: Run `lmt` and fail if differences are detected
+      - name: Run LMT
+        run: |
+          lmt docs/proofs.md
+          lmt docs/invariants.md
+          lmt docs/tree_manipulation.md
+          lmt docs/grug_ics23.md
+          lmt docs/proof_types.md
+          # Check that it is up to date
+          git diff --exit-code \
+            || ( echo ">>> ERROR: Tangled files are out of sync." &&  exit 1)
 
   quint-typecheck:
     name: Typecheck
@@ -74,7 +74,7 @@ jobs:
           node-version: "18"
       - run: npm install -g @informalsystems/quint
       - run: quint test --max-samples=$MAX_SAMPLES quint/test/test_all.qnt
-  
+
   quint-simulations-fancy:
     name: Simulate fancy
     runs-on: ubuntu-latest
@@ -91,7 +91,7 @@ jobs:
           node-version: "18"
       - run: npm install -g @informalsystems/quint
       - run: quint run --max-samples=$MAX_SAMPLES --max-steps=$MAX_STEPS --invariant=allInvariants --step=step_fancy apply_state_machine.qnt
-    
+
   quint-simulations-simple:
     name: Simulate simple
     runs-on: ubuntu-latest
@@ -125,7 +125,7 @@ jobs:
           node-version: "18"
       - run: npm install -g @informalsystems/quint
       - run: quint run --max-samples=$MAX_SAMPLES --max-steps=$MAX_STEPS --invariant=allInvariants --step=step_simple pruning_state_machine.qnt
-  
+
   quint-simulations-prune-fancy:
     name: Simulate fancy pruning
     runs-on: ubuntu-latest
