Automated deployment of devnet and server provisioning (#646)
* Add ansible init

* Add docker

* Enable fail2ban

* Add CI docker build steps

* Add image cleanup

* Optimize docker build

* Add current git version

* Add parallel building

* Fix

* Fix

* Fix ENV

* Fix

* Use latest Rust

* Fix

* Fix

* Fix

* Disable optimizer

* Fix fmt

* Remove multi platform builds

* Push docker images

* Fix

* Fix

* Fix

* Fix

* Add description

* Reenable multi arch

* add 2 steps

* Skip cometbft build if already exists

* Fix

* Move to self hosted

* Use self hosted runner

* Enable arm builds on self hosted

* Fix

* Fix

* Fix

* Enable cross

* Fix

* Reenable

* Enable back

* Fix

* Switch docker image

* Force CI

* Add multi stage

* Fix

* Fix

* Fix

* Fix

* Add cache

* Use single cross image

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix commit ids

* Fix

* Add docker bake

* Update builders

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Update

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix Rust

* Fix

* Fix

* Fix

* Fix

* Fix

* Add postgres role

* Add a /up route

* Fix

* Add a test

* Sync

* Fix requirements

* Add tailscale check

* Switch away from user within docker images

* Fix

* Fix

* Install katex

* Fix

* Fix genesis

* Fix

* Fix db host

* More fixes

* Enable genesis pub key template

* More permissive graphiql

* Use current git commit for dango

* Fix

* Fix

* Fix

* Deploy the current dango docker image

* Add git_commit in up

* Fix fmt

* Fix

* Fix docker

* Add cold deploy

* Add deploy key

* Fix

* Fix python

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Fix

* Disable tailscale ssh

* Fix

* Fix

* Fix

* Fix

* Add cold provisioning

* Fix

* Only deploy for main

* Fix

* Update deploy/roles/mdbook/tasks/main.yml

Co-authored-by: ellipsis-dev[bot] <65095814+ellipsis-dev[bot]@users.noreply.github.com>

* Update deploy/setup-github-runner-hosts.yml

Co-authored-by: ellipsis-dev[bot] <65095814+ellipsis-dev[bot]@users.noreply.github.com>

* Update dango/cli/src/main.rs

* rename `HealthResponse` to `UpResponse` to avoid confusion with margin account health response

---------

Co-authored-by: Larry <26318510+larry0x@users.noreply.github.com>
Co-authored-by: ellipsis-dev[bot] <65095814+ellipsis-dev[bot]@users.noreply.github.com>

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -15,6 +15,7 @@ on:
       - "develop"
     paths:
       - ".github/workflows/rust.yml"
+      - "deploy/**"
       - "dango/**"
       - "docker/**"
       - "grug/**"
@@ -29,6 +30,7 @@ on:
       - "*"
     paths:
       - ".github/workflows/rust.yml"
+      - "deploy/**"
       - "dango/**"
       - "docker/**"
       - "grug/**"
@@ -68,7 +70,7 @@ jobs:
       #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
       - name: Run rustfmt checks
-        run: cargo +nightly fmt --check --all
+        run: rustup run nightly cargo fmt --check --all
 
   test:
     needs: [format]
@@ -84,7 +86,7 @@ jobs:
       DB_HOST: postgres
     # services:
     #   postgres:
-    #     image: postgres
+    #     image: postgres:17
     #     env:
     #       POSTGRES_PASSWORD: postgres
     #     options: >-
@@ -106,15 +108,15 @@ jobs:
       #   run: |
       #     createdb -U postgres -h postgres "$PGDATABASE"
 
-      - uses: actions/cache@v4
-        with:
-          path: |
-            ${HOME}/.cargo/bin/
-            ${HOME}/.cargo/registry/index/
-            ${HOME}/.cargo/registry/cache/
-            ${HOME}/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+      # - uses: actions/cache@v4
+      #   with:
+      #     path: |
+      #       ${HOME}/.cargo/bin/
+      #       ${HOME}/.cargo/registry/index/
+      #       ${HOME}/.cargo/registry/cache/
+      #       ${HOME}/.cargo/git/db/
+      #       target/
+      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
       - name: Run clippy
         run: cargo clippy --bins --tests --benches --examples --all-features --all-targets -- -D warnings
@@ -205,9 +207,9 @@ jobs:
 
       - name: Set GIT_COMMIT
         run: |
-          cp dango/cli/src/git_info.rs dango/cli/src/git_info.rs.in
-          sed "s/{{GIT_COMMIT}}/${{ env.GIT_COMMIT }}/" dango/cli/src/git_info.rs.in > dango/cli/src/git_info.rs
-          rm dango/cli/src/git_info.rs.in
+          cp grug/app/src/git_info.rs grug/app/src/git_info.rs.in
+          sed "s/{{GIT_COMMIT}}/${{ env.GIT_COMMIT }}/" grug/app/src/git_info.rs.in > grug/app/src/git_info.rs
+          rm grug/app/src/git_info.rs.in
 
       - uses: docker/setup-buildx-action@v3
 
@@ -277,3 +279,42 @@ jobs:
 
             docker manifest push ghcr.io/left-curve/left-curve/dango:latest
           fi
+
+  deploy-dango:
+    if: github.ref == 'refs/heads/main'
+    permissions:
+      packages: read
+    needs: [push-manifest]
+    runs-on: [self-hosted]
+    env:
+      DANGO_DB_PASSWORD: ${{ secrets.DANGO_DB_PASSWORD }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check DEPLOY_KEY is set
+        run: |
+          if [ -z "${{ secrets.DEPLOY_KEY }}" ]; then
+            echo "Missing DEPLOY_KEY secret"
+            exit 1
+          fi
+      - name: Start SSH agent
+        uses: webfactory/ssh-agent@v0.7.0
+        with:
+          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
+      - name: Ensure ~/.local/bin is in PATH
+        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
+      - name: Install Ansible & Docker SDK
+        run: |
+          pipx install ansible
+          pipx ensurepath
+          ln -f -s ~/.local/pipx/venvs/ansible/bin/ansible-galaxy ~/.local/bin/ansible-galaxy
+          ln -sf ~/.local/pipx/venvs/ansible/bin/ansible-playbook ~/.local/bin/ansible-playbook
+          cd deploy
+          ansible-galaxy collection install -r requirements.yml
+      - name: Run Ansible playbook
+        run: |
+          cd deploy
+          pipx ensurepath
+          ansible-playbook dango.yml \
+            --skip-tags setup \
+            -e dango_image_tag=${{ env.GIT_COMMIT }} \
+            -e "dango_db_password=$DANGO_DB_PASSWORD"
